import { StyleSheet } from "react-native";
import {colors} from '../../../../Utils/Colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.SecondaryColor, // '#252932',   //'#F9FAFB',
    padding: 10,
    marginBottom: 10,
  },
  loadMoreButton: {
    backgroundColor: colors.SecondaryColor,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginVertical: 6,
    elevation: 3,
    // minWidth: 140,
  },

  loadMoreButtonDisabled: {
    backgroundColor: '#333',
  },

  loadMoreText: {
    color: '#ccc',
    fontWeight: '600',
  },

  endOfList: {
    alignItems: 'center',
    marginVertical: 16,
  },

  endOfListText: {
    color: '#999',
    fontSize: 12,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabContainer: {
    flexDirection: 'row',
    // backgroundColor: '',   //'#F3F4F6',
    borderRadius: 8,
    padding: 4,
    marginBottom: 10,
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 16,
    marginHorizontal: 2,
  },
  tabText: {
    marginLeft: 5,
    fontSize: 12,
    fontWeight: '600',
  },
  countContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 10,
  },
  countBox: {
    backgroundColor: '#000', //'#9CA3AF',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  selectedCountBox: {
    backgroundColor: '#FDD122',
    padding: 10,
    borderRadius: 20,
    position: 'relative',
  },
  badge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFF',
  },
  badgeText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  countText: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#FFF',
  },
  tabContent: {
    height: 300,
  },
  bundleSaleMainContainer: {
    marginTop: 20,
    marginBottom: 16,
  },
  bundleSaleCard: {
    backgroundColor: '#1a1a1a',
    borderRadius: 16,
    // borderWidth: 2,
    // borderColor: '#FDD122',
    overflow: 'hidden',
    // shadowColor: '#FDD122',
    // shadowOffset: { width: 0, height: 4 },
    // shadowOpacity: 0.2,
    // shadowRadius: 8,
    // elevation: 5,
  },
  bundleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    backgroundColor: '#222',
  },
  bundleHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  bundleIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: 'rgba(253, 209, 34, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(253, 209, 34, 0.3)',
  },
  bundleHeaderText: {
    marginLeft: 16,
    flex: 1,
  },
  bundleTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFF',
    marginBottom: 4,
  },
  bundleSubtitle: {
    fontSize: 13,
    color: '#999',
    fontWeight: '500',
  },
  bundleContent: {
    backgroundColor: '#1a1a1a',
  },
  bundleDivider: {
    height: 1,
    backgroundColor: 'rgba(253, 209, 34, 0.2)',
    marginHorizontal: 20,
  },
  submitButton: {
    backgroundColor: '#FFD700',
    marginTop: 10,
    color: '#000',
    padding: 10,
    alignItems: 'center',
    borderRadius: 10,
  },
  tabSection: {
    height: '100%',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginVertical: 10,
    color: '#fff',
  },
  productList: {
    paddingBottom: 16,
  },
  productCard: {
    flexDirection: 'row',
    backgroundColor: '#121212', // '#FFF',
    borderRadius: 12,
    padding: 10,
    marginBottom: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    minHeight: 100,
  },
  selectedProductCard: {
    flexDirection: 'row',
    backgroundColor: '#222', //'#EFF6FF',
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#fbdd74',
    // borderWidth:1,
    // borderColor:'#555',
    padding: 12,
    marginBottom: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    position: 'relative',
  },
  productNumberBadge: {
    position: 'absolute',
    top: -8,
    left: -8,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#fbdd74',
    justifyContent: 'center',
    alignItems: 'center',
  },
  productNumberText: {
    color: '#000',
    fontSize: 12,
    fontWeight: 'bold',
  },
  productImage: {
    width: 70,
    height: 70,
    borderRadius: 8,
    backgroundColor: '#F3F4F6',
  },
  productInfo: {
    flex: 1,
    marginLeft: 12,
  },
  productTitle: {
    fontWeight: 'bold',
    fontSize: 15,
    color: '#eee', //'#1F2937',
    marginBottom: 6,
    lineHeight: 20,
  },
  productMeta: {
    flexDirection: 'row',
    gap:5,
    // justifyContent: 'space-between',
    alignItems: 'center',
  },
  stockContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stockText: {
    fontSize: 12,
    color: '#666',
    marginLeft: 4,
  },
  priceText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  smallPriceText: {
    fontSize: 10,
    color: '#fff',
  },
  auctionPrices: {
    alignItems: 'flex-end',
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    //  backgroundColor: '#ECFDF5',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginLeft: 8,
  },
  addButtonText: {
    color: '#FDD122',
    fontWeight: '600',
    fontSize: 12,
    marginLeft: 4,
  },
  addButtonDisabled: {
    opacity: 0.5,
  },
  addButtonTextDisabled: {
    color: '#666',
  },
  // Inline quantity stepper styles
  inlineQuantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 8,
  },
  quantityLabel: {
    fontSize: 12,
    color: '#fff',
    fontWeight: '600',
  },
  inlineQuantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  inlineQuantityButton: {
    backgroundColor: '#FDD122',
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inlineQuantityButtonDisabled: {
    backgroundColor: '#555',
    opacity: 0.5,
  },
  inlineQuantityText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    minWidth: 30,
    textAlign: 'center',
  },
  removeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor: '#FEF2F2',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 16,
    marginLeft: 4,
  },
  removeButtonText: {
    color: '#F44336',
    fontWeight: '600',
    fontSize: 12,
    marginLeft: 4,
  },
  priceInputContainer: {
    marginTop: 6,
  },
  priceDisplayContainer: {
    backgroundColor: '#1a1a1a',
    borderRadius: 6,
    padding: 8,
    borderWidth: 1,
    borderColor: '#555',
  },
  priceDisplayText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FDD122',
  },
  quantityInputContainer: {
    marginTop: 8,
  },
  quantityControlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    gap: 8,
  },
  quantityButton: {
    backgroundColor: '#FDD122',
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityButtonDisabled: {
    backgroundColor: '#555',
    opacity: 0.5,
  },
  quantityInput: {
    flex: 1.5,
    borderWidth: 2,
    borderColor: '#FDD122',
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 12,
    marginHorizontal: 8,
    backgroundColor: '#1a1a1a',
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    minWidth: 80,
  },
  auctionInputsContainer: {
    marginTop: 8,
  },
  auctionInputWrapper: {
    marginBottom: 6,
  },
  inputLabel: {
    fontSize: 12,
    color: '#fff', // '#6B7280',
    marginBottom: 2,
  },
  priceInput: {
    borderWidth: 1,
    borderColor: '#555',
    borderRadius: 6,
    padding: 6,
    backgroundColor: '#222', //'#FFF',
    color: '#fff',
    fontSize: 14,
  },
  errorInput: {
    borderColor: '#EF4444',
    backgroundColor: '#222',
  },
  errorText: {
    color: '#EF4444',
    fontSize: 10,
    marginTop: 2,
  },
  followersContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
    justifyContent: 'flex-start',
  },
  followersLabel: {
    fontSize: 14,
    color: '#6B7280',
    marginRight: 8,
  },
  emptyState: {
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#222',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#666',
    // borderStyle: 'dashed',
  },
  emptyStateText: {
    marginTop: 8,
    color: '#ccc',
    fontSize: 14,
  },
  disabledProductTypeContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    minHeight: 250,
  },
  disabledProductTypeCard: {
    backgroundColor: '#1a1a1a',
    borderRadius: 16,
    padding: 32,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#333',
    maxWidth: 400,
  },
  disabledProductTypeTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FDD122',
    marginTop: 16,
    marginBottom: 12,
    textAlign: 'center',
  },
  disabledProductTypeMessage: {
    fontSize: 14,
    color: '#ccc',
    textAlign: 'center',
    lineHeight: 22,
  },
  // Giveaway specific styles
  giveawaySelectedCard: {
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#FDD122',
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    position: 'relative',
  },
  giveawayCardContent: {
    width: '100%',
  },
  giveawayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  giveawayHeaderText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FDD122',
    marginLeft: 8,
  },
  giveawayProductInfo: {
    flexDirection: 'row',
    backgroundColor: '#222',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  giveawayProductImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    backgroundColor: '#333',
  },
  giveawayProductDetails: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'center',
  },
  giveawayProductLabel: {
    fontSize: 11,
    color: '#888',
    marginBottom: 4,
  },
  giveawayProductTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 6,
  },
  giveawayStockInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  giveawayStockText: {
    fontSize: 12,
    color: '#888',
    marginLeft: 4,
  },
  giveawayQuantitySection: {
    backgroundColor: '#222',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
  },
  giveawayQuantityLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 8,
  },
  giveawayQuantityInput: {
    borderWidth: 2,
    borderColor: '#FDD122',
    borderRadius: 8,
    padding: 12,
    backgroundColor: '#1a1a1a',
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 8,
  },
  giveawayQuantityInfo: {
    fontSize: 12,
    color: '#aaa',
    marginBottom: 10,
    lineHeight: 18,
  },
  giveawayInfoBox: {
    flexDirection: 'row',
    backgroundColor: '#2a2a2a',
    borderRadius: 6,
    padding: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#FDD122',
  },
  giveawayInfoText: {
    fontSize: 11,
    color: '#bbb',
    marginLeft: 8,
    flex: 1,
    lineHeight: 16,
  },
  giveawayQuantityInfoSection: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#222',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    gap: 8,
  },
  giveawayQuantityInfoText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  giveawayFollowSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#222',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
  },
  giveawayFollowLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  giveawayRemoveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2a1a1a',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#F44336',
  },
  giveawayRemoveText: {
    color: '#F44336',
    fontWeight: '600',
    fontSize: 13,
    marginLeft: 6,
  },
  // Giveaway available products layout
  giveawayAvailableCard: {
    backgroundColor: '#121212',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  giveawayAvailableTop: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  giveawayAvailableInfo: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'center',
  },
  giveawayQuantityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#333',
  },
  giveawayQuantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    marginLeft: 12,
  },
  giveawayQtyButton: {
    backgroundColor: '#FDD122',
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  giveawayQtyInput: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#FDD122',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: '#1a1a1a',
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    minWidth: 50,
    maxWidth: 80,
  },
  giveawayAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#222',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    marginLeft: 12,
    borderWidth: 1,
    borderColor: '#FDD122',
  },
  giveawayConfigButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#222',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FDD122',
    alignSelf: 'flex-end',
  },
  giveawayConfigButtonText: {
    color: '#FDD122',
    fontWeight: '600',
    fontSize: 13,
    marginLeft: 6,
  },
  giveawayInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#222',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    gap: 8,
  },
  tierIcon: {
    fontSize: 24,
  },
  tierDescription: {
    fontSize: 11,
    color: '#888',
    marginTop: 2,
  },
  followDescription: {
    fontSize: 11,
    color: '#888',
    marginTop: 2,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: '#1a1a1a',
    borderRadius: 16,
    maxWidth: 500,
    width: '100%',
    maxHeight: '90%',
    // borderWidth: 2,
    // borderColor: '#FDD122',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FDD122',
    flex: 1,
    marginLeft: 8,
  },
  modalCloseButton: {
    padding: 4,
  },
  modalProductInfo: {
    flexDirection: 'row',
    padding: 10,
    flex:1,
    // backgroundColor: '#FDD122',
    // margin: 16,
    marginBottom: 0,
    borderRadius: 12,
    // borderWidth: 1,
    // borderColor: '#FDD122',
  },
  modalProductImage: {
    width: 60,
    height: 60,
    marginRight:5,
    borderRadius: 8,
    backgroundColor: '#333',
  },
  modalProductTitle: {
    fontSize: 14,
    fontWeight: '600',
    // marginLeft:5,
    color: '#fff',
    marginBottom: 4,
  },
  modalProductStock: {
    fontSize: 12,
    color: '#ccc',
  },
  modalSection: {
    padding: 16,
  },
  modalSectionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 12,
  },
  modalQuantityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  modalQuantityButton: {
    backgroundColor: '#FDD122',
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalQuantityInput: {
    borderWidth: 2,
    borderColor: '#FDD122',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: '#222',
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    minWidth: 80,
  },
  tierGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    // flexdirection: 'row',
    gap: 7,
  },
  tierCard: {
    width: '48%',
    backgroundColor: '#222',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    borderWidth: 2,
  },
  tierCardSelected: {
    backgroundColor: '#FDD122',
  },
  tierLabel: {
    fontSize: 13,
    fontWeight: 'bold',
    marginTop: 8,
    marginBottom: 4,
  },
  tierDesc: {
    fontSize: 10,
    color: '#888',
    textAlign: 'center',
    lineHeight: 14,
  },
  modalToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#222',
    borderRadius: 12,
    padding: 16,
  },
  modalToggleDesc: {
    fontSize: 12,
    color: '#888',
    marginTop: 4,
  },
  modalActions: {
    flexDirection: 'row',
    padding: 16,
    gap: 12,
  },
  modalCancelButton: {
    flex: 1,
    backgroundColor: '#333',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  modalCancelText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  modalConfirmButton: {
    flex: 1,
    backgroundColor: '#FDD122',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  modalConfirmText: {
    color: '#000',
    fontSize: 14,
    fontWeight: 'bold',
  },
  // Parent-child hierarchy styles
  parentProductCard: {
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#FDD122',
  },
  parentProductCardBuyNow: {
    backgroundColor: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#FDD122',
    paddingVertical: 16,
    minHeight: 90,
  },
  parentProductImage: {
    width: 60,
    height: 60,
    borderRadius: 6,
  },
  parentProductTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    lineHeight: 20,
  },
  variantInfoContainerBuyNow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(253, 209, 34, 0.15)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginTop: 6,
    alignSelf: 'flex-start',
  },
  expandIconContainer: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    // marginRight: 8,
  },
  variantInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(253, 209, 34, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  variantCountText: {
    fontSize: 12,
    color: '#FDD122',
    fontWeight: '600',
    marginLeft: 4,
  },
  expandHintContainer: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  expandHintText: {
    fontSize: 11,
    color: '#FDD122',
    fontWeight: '600',
  },
  variantProductCard: {
    backgroundColor: 'rgba(50, 50, 50, 0.5)',
    // backgroundColor:'red',
    maxHeight: 110,
    marginLeft: 24,
    borderLeftWidth: 2,
    borderLeftColor: '#555',
  },
  variantIndentLine: {
    width: 20,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  variantConnector: {
    width: 12,
    height: 12,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    borderColor: '#555',
    borderBottomLeftRadius: 8,
  },
  variantImage: {
    width: 55,
    height: 55,
  },
  variantTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  variantTitle: {
    fontSize: 13,
    flex: 1,
  },
  variantBadge: {
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  variantBadgeText: {
    fontSize: 10,
    color: '#60A5FA',
    fontWeight: '600',
  },
  // Buy Now quantity controls styles
  buyNowControlsContainer: {
    marginTop: 8,
  },
  buyNowPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  buyNowPriceInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#FDD122',
    borderRadius: 6,
    padding: 6,
    marginLeft: 8,
    backgroundColor: '#1a1a1a',
    color: '#FDD122',
    fontSize: 14,
    fontWeight: '600',
  },
  buyNowQuantityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  smallQuantityButton: {
    backgroundColor: '#FDD122',
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityDisplayText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    minWidth: 30,
    textAlign: 'center',
  },
  maxQtyText: {
    fontSize: 11,
    color: '#888',
    marginLeft: 8,
  },
  // Tier selection row styles for selected giveaway cards
  tierSelectionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  tierSelectButton: {
    flex: 1,
    minWidth: '22%',
    backgroundColor: '#222',
    borderRadius: 8,
    padding: 8,
    alignItems: 'center',
    borderWidth: 1,
  },
  tierSelectButtonActive: {
    backgroundColor: 'rgba(253, 209, 34, 0.15)',
  },
  tierSelectIcon: {
    fontSize: 16,
    marginBottom: 2,
  },
  tierSelectLabel: {
    fontSize: 10,
    fontWeight: '600',
  },
});
export default styles;
